name: 'Setup Maven'
description: 'Set up a specific version of the Mavne and add the
   command-line tool to the PATH'
author: 'jvalkeal'
inputs:
  maven-version:
    description: 'The Maven version to make available on the path. Takes a whole
       or semver Maven version, or 3.x syntax (e.g. 3.6 => Maven 3.x)'
    required: false
  maven-file:
    description: 'Path to where the compressed Maven is located. The path could
       be in your source repository or a local path on the agent.'
    required: false
  maven-mirror:
    description: 'Uri hosting Maven3 mirror packages.'
    required: false
    default: 'https://archive.apache.org/dist/maven/maven-3/'
runs:
  using: 'node12'
  main: 'dist/index.js'
