name: Demo1

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: win
            os: windows-latest
            java: 17
          - nickname: macos
            os: macos-latest
            java: 17
          - nickname: linux
            os: ubuntu-latest
            java: 17
    name: Build ${{ matrix.nickname }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: ${{ matrix.java }}
    - uses: jvalkeal/setup-maven@master
      with:
        maven-version: 3.6.3
    - name: Print win
      if: runner.os == 'Windows'
      run: |
        $env:M2_HOME
        mvn --version
    - name: Print other
      if: runner.os != 'Windows'
      run: |
        echo $M2_HOME
        mvn --version
